### ISSUE TITLE
Add a CORS policy to the master playlist buckets

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-stale-playlist-detector#26]
It turns out we'll need a permissive CORS policy for the buckets when using the master playlist from a browser page loaded from another location.

`THEOplayer.js:39 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) Could not load the manifest file. Make sure the source is set correctly and that CORS support is enabled.`

Here is a policy I've used in the past:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>

```

**Comment by vengahil** [comment]
When aws S3 origin is played via CloudFront Url, the CORS setting required  : GET, HEAD, DELETE required for Theoplayer, whilw S3 Url works only with GET.

JSON
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD",
            "DELETE"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [],
        "MaxAgeSeconds": 3000
    }
]

In case of HLSjs player, GET & HEAD methods are required.
Theoplaer tested - 2.8.2
